[features]
seeds = false
skip-lint = false
[programs.localnet]
nft_minter = "4Skqz2saV9eJoPerAdpt1Mn4ur3mX4qCZkvgKguBQpFB"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
